### ISSUE TITLE
cmake isnt working

### ISSUE THREAD

**Issue by meowgoober** [sppmacd/midiplayer#1]
im on fedora linux and whenever i try to run cmake it just does this
dorker@fedora:~/midiplayer/build$ cmake ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" (requested
  version 8.0.0) with any of the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
dorker@fedora:~/midiplayer/build$

**Comment by sppmacd** [comment]
Hello, thanks for the report! Did you install [dependencies](https://github.com/sppmacd/midiplayer/blob/master/docs/Build.md#1-install-dependencies)?

**Comment by meowgoober** [comment]
i installed the depencies then i got this
dorker@fedora:~/Videos$ git clone https://github.com/sppmacd/midiplayer.git
Cloning into 'midiplayer'...
remote: Enumerating objects: 1664, done.
remote: Counting objects: 100% (451/451), done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 1664 (delta 277), reused 294 (delta 160), pack-reused 1213
Receiving objects: 100% (1664/1664), 1.28 MiB | 431.00 KiB/s, done.
Resolving deltas: 100% (1167/1167), done.
dorker@fedora:~/Videos$ cd midiplayer/
dorker@fedora:~/Videos/midiplayer$ mkdir build
dorker@fedora:~/Videos/midiplayer$ cd build/
dorker@fedora:~/Videos/midiplayer/build$ cmake ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" (requested
  version 8.0.0) with any of the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
dorker@fedora:~/Videos/midiplayer/build$

**Comment by sppmacd** [comment]
I switched this to use FetchContent, try pulling and building again

**Comment by meowgoober** [comment]
i think its trying to find a package configuratine file by SFML
dorker@fedora:~/Music/midiplayer$ mkdir build
cd build
cmake ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Version: 10.2.1
-- Build type: 
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" (requested
  version 2.5.1) with any of the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
dorker@fedora:~/Music/midiplayer/build$

**Comment by sppmacd** [comment]
Hmm, maybe try to build & install SFML from source and then set that `CMAKE_PREFIX_PATH` to your install location (`/usr/local/` probably)
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local`

**Comment by sppmacd** [comment]
Also I'm not sure if you really installed *all* dependencies... did you run `sudo dnf -y install fmt SFML rtmidi` or something like that?

**Comment by meowgoober** [comment]
Never mind. i distro hopped to pop and got all packages working. Thanks for your help tho!

**Comment by meowgoober** [comment]
welp bye bye!
