### ISSUE TITLE
trying to acess an empty image?

### ISSUE THREAD

**Issue by meowgoober** [sppmacd/midiplayer#2]
dorker@pop-os:~/midiplayer/build$ ./midiplayer play Addict_-_Hazbin_Hotel.mid 
./midiplayer (MIDIPlayer) dev (Apr  5 2024 01:18:49)
INFO: Resource path: /usr/local/share/midiplayer
INFO: Shaders loaded
INFO: Font loaded
INFO: Textures loaded
WARNING: No display font is specified. Using debug font.
INFO: Config file successfully reloaded from config.cfg
Failed to load image "/usr/local/share/midiplayer/icon32.png". Reason: Unable to open file
Trying to access the pixels of an empty image
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  169
  Current serial number in output stream:  176

**Comment by sppmacd** [comment]
Did you run `sudo make install` (then you should be able to use just `midiplayer`)?

Or just build with `-DMIDIPLAYER_PORTABLE_INSTALL=1` and then just `./midiplayer` should work

**Comment by meowgoober** [comment]
yes i did. its trying to enter an empty image. its nothing with the build.
dorker@pop-os:~$ cd Downloads/
dorker@pop-os:~/Downloads$ midiplayer play midis_MyOrdinaryLife.mid 
midiplayer (MIDIPlayer) dev (Apr  5 2024 16:43:12)
INFO: Resource path: /usr/local/share/midiplayer
INFO: Shaders loaded
INFO: Font loaded
INFO: Textures loaded
WARNING: Failed to setup watch for config.cfg: No such file or directory
WARNING: No display font is specified. Using debug font.
Failed to load image "/usr/local/share/midiplayer/icon32.png". Reason: Unable to open file
Trying to access the pixels of an empty image
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  169
  Current serial number in output stream:  176
dorker@pop-os:~/Downloads$

**Comment by sppmacd** [comment]
oops my bad. just place some random 32x32 png image there, should work for now while I fix this

**Comment by meowgoober** [comment]
do i provide a soundfont since it dosent play sounds?

**Comment by sppmacd** [comment]
There is no direct support for instrument plugins/soundfonts yet.

You could
- specify a `-m 0` flag (`midiplayer -m 0 play something.mid`)
- open some DAW and set "Midi Through" as MIDI input

I got this working with pipewire and LMMS.
![image](https://github.com/sppmacd/midiplayer/assets/42967349/7beafe7e-7479-4737-b695-c6765d217b18)
In (at least) pipewire you should be able to connect these directly
![image](https://github.com/sppmacd/midiplayer/assets/42967349/997bc26c-83a6-455f-8f63-0dc6caed132d)
I don't know if this will work in pulseaudio.

**Comment by sppmacd** [comment]
Obviously, if you have some real MIDI device which can play sound, you can specify it as `-m` argument too (run `midiplayer list-midi-devices` for which number you need to enter there)

**Comment by meowgoober** [comment]
Got it.
